name: "Unit Tests"

on:
  push:
  pull_request:

jobs:
  test:
    name: "Golang Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Golang Tests"
        run: go test -v
